### PR TITLE
fixed navbar responsiveness

### PR DESCRIPTION
**Pull request by vashukashyap**
# What this PR do?
#21 fixed Navbar responsive for both desktop and mobile.

# Expected behaviour.
the Navbar should display properly on desktop and mobile

# Additional info.

## Desktop
Screenshot (16)

## Mobile
Screenshot (17) 
Screenshot (18)

### CODE REVIEW

**Comment by vashukashyap** [comment]
Kindly check my PR please

**Review by Iamdivyak — COMMENTED** [review]
give the navbar background a blur effect on scrolling.
give a 1.5rem margin to the 'close menu' button

**Review by Iamdivyak — CHANGES_REQUESTED** [review]
give the navbar background a blur effect on scrolling.
give a 1.5rem margin to the 'close menu' button

**Comment by vashukashyap** [comment]
I have committed the changes, can you review it please

**Review by Iamdivyak — APPROVED** [review]

**Comment by gauravsingh1281** [comment]
Screenshot 2023-10-14 200757
Screenshot 2023-10-14 200901


Hii @vashukashyap rentals nav links missing in the navbar and I want the above mobile design for mobile view.

**Comment by vashukashyap** [comment]
I have modified the Navbar , please review now.

**Comment by gauravsingh1281** [comment]
@vashukashyap please resolve merge conflict

**Comment by gauravsingh1281** [comment]
> I have modified the Navbar , please review now.

@vashukashyap please resolve merge conflict.

**Comment by vashukashyap** [comment]
I have resolved the merge conflict. review it please!

**Review by gauravsingh1281 — APPROVED** [review]

**Comment by gauravsingh1281** [comment]
Thank you for your contribution @vashukashyap

**Comment by vashukashyap** [comment]
thankyou sir, is there any other issue where I can help?

**Pull request merged**
