### PR TITLE
enhance(nav): issue#27 create toggle nav bar for mobile

### PR DESCRIPTION
**Pull request by DannyK05**

### CODE REVIEW

**Comment by DannyK05** [comment]
This is the update for the mobile nav 
I tweaked it a little and added a fixed nav with green bg color(I can change it if you don't want that)
Mobile
Screenshot (73)
Screenshot (70)
Screenshot (71)

**Comment by DannyK05** [comment]
@gauravsingh1281
Seems like there is a merge conflict.

**Comment by gauravsingh1281** [comment]
hii @DannyK05 Thank you for your contribution 😇. But this issue has already been resolved by this PR #38.

**Comment by DannyK05** [comment]
Alright

**Pull request closed without merging**
