### PR TITLE
Create contact us section for the Rentalog from its figma design. Issue#8

### LINKED ISSUE #8: Create contact us section for the Rentalog from its figma design.
Figma Design Link - https://www.figma.com/file/9WhtUQT7s5ogTiDTp90PxI/RENTALOG-WEB-DESIGN?type=design&node-id=0-1&mode=design&t=ZNeyPXk16TlWB6I6-0

### PR DESCRIPTION
**Pull request by Kashif-Saleem-Ghuman**
Hello Code Reviewer :wave: 
Animated GIF
:green_circle: In this milestone:

- I have created the Contact Section including the contact form.
- I have made it mobile responsive 
- I have used solely tailwind classes to design according to the figma design provided
- Here are the screenshots :
[screenshots.pdf](https://github.com/gauravsingh1281/Rentalog-Rent-Management-Web-App-For-Landlords/files/12193210/screenshots.pdf)
Closes #8

### CODE REVIEW

**Comment by Iamdivyak** [comment]
please resolve conflicts

**Comment by gauravsingh1281** [comment]
### Original Footer
Screenshot 2023-07-28 184057

### Footer Preview from your code
Screenshot 2023-07-28 184031

**Comment by gauravsingh1281** [comment]
@Kashif-Saleem-Ghuman Please Fix the footer section Background in your code.

**Comment by Kashif-Saleem-Ghuman** [comment]
@gauravsingh1281 Sure, I will fix it, however, please note I did not make the footer, I was working on the Contact section.

**Comment by gauravsingh1281** [comment]
@Kashif-Saleem-Ghuman Yes I know but this issue comes in your Pull request preview. Please share the screenshot of your local development preview of the footer section.

**Comment by Kashif-Saleem-Ghuman** [comment]
@gauravsingh1281 Hi,

I have fixed the footer issue. Here is a screenshot of how it looks now:
footer

**Comment by gauravsingh1281** [comment]
@Kashif-Saleem-Ghuman Good Work 👍

**Comment by Kashif-Saleem-Ghuman** [comment]
@gauravsingh1281  Thank you very much for the appreciation :). I want to contribute more. Please you may assign me another issue.

**Pull request merged**
