### PR TITLE
Admin dashboard issue#25

### LINKED ISSUE #25: Design and Create Rentalog Admin Dashboard.
### Take Inspiration From [Rentalog.in](https://rentalog-web-app.azurewebsites.net/dashboard) Admin Dashboard.

Screenshot 2023-07-28 191846

### PR DESCRIPTION
**Pull request by Kashif-Saleem-Ghuman**
**Hi Code Reviewer** :wave: 
Animated GIF
:green_circle: In this milestone:

- [ ] I have created the Dashboard. Here is a video demonstration of what I have implemented:
[Video Demonstartion](https://www.loom.com/share/f056cdbc721143ab8f33368bf8973517?sid=a437c967-5c41-433b-9f30-f01a8238956f)

closes #25

### CODE REVIEW

**Comment by Kashif-Saleem-Ghuman** [comment]
HI @gauravsingh1281,

Hope you are well! Kindly review the PR. 

Regards,
Kashif Saleem

**Comment by gauravsingh1281** [comment]
Hey @Kashif-Saleem-Ghuman I have looked at your PR and found that u have made some changes in the homepage's navbar and made it different from its Figma design. So Please make it look like the Figma design that I have provided.

**Comment by gauravsingh1281** [comment]
@Kashif-Saleem-Ghuman And the admin dashboard page comes after user authentication which means that when the user is successfully logged in than it will redirect to the admin dashboard.

**Comment by Kashif-Saleem-Ghuman** [comment]
Hi @gauravsingh1281 ,

I have refactored as per your suggestions. Please check.

**Comment by gauravsingh1281** [comment]
@Kashif-Saleem-Ghum 
Fix the homepage's navbar and make it look like the Figma design that I have provided.
Figma Design - https://www.figma.com/file/9WhtUQT7s5ogTiDTp90PxI/RENTALOG-WEB-DESIGN?type=design&node-id=0-1&mode=design&t=giHe43ij31sBYaaw-0

**Comment by gauravsingh1281** [comment]
Screenshot 2023-09-13 195006

@Kashif-Saleem-Ghuman You're not understanding what I mean. I only want you to remove the white background from the navbar so that it matches the Figma design and header section background color

**Pull request closed without merging**
