### PR TITLE
added: about us page

### PR DESCRIPTION
**Pull request by Roy404Dev**
This change resolves: #6
Hope it's good for u.

### CODE REVIEW

**Comment by gauravsingh1281** [comment]
@Roy404Dev  logo and the rent-board image are not visible fix this.

**Comment by Roy404Dev** [comment]
could be the issue with image path, lemme check.

**Comment by gauravsingh1281** [comment]
Screenshot 2023-07-21 135601

@Roy404Dev Still not showing

**Comment by gauravsingh1281** [comment]
It also has merge conflict resolve it.

**Pull request closed without merging**
